DROP TABLE IF EXISTS DemoPage;
CREATE TABLE IF NOT EXISTS DEMOPAGE(
    Id INTEGER PRIMARY KEY AUTOINCREMENT,
    Name NVARCHAR(2048) NULL,
    Ext VARCHAR(10) NULL,
    LocalExt VARCHAR(10) NULL,
    LocalMirrorFile INTEGER
);